name: C/C++ CI

on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y autoconf automake

    - name: Generate configure script
      run: autoreconf -i
      
    - name: Set execute permissions
      run: chmod +x ./configure.ac

  name-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: configure
      run: ./configure
      
    - name: Build with make
      run: make
      
    - name: make
      run: make

    - name: make check
      run: make check
      
    - name: make distcheck
      run: make distcheck
