name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v4
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y autoconf automake

    - name: Generate configure script
      run: autoreconf -i
    - name: Set execute permissions
      run: chmod +x ./configure.ac
    - name: Build with make
      run: make
    - name: Check PATH
      run: echo $PATH
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
